### ISSUE TITLE
Derive, Derive TEOS-10, split, psas for SBE19

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [sean-rohan-NOAA/gapctd#3]
Add psa files for:
1. Splitting upcasts and downcasts
2. Deriving vars

**Comment by coleary-noaa** [comment]
completed split & derive TEOS-10 .psa 

error for derive: "Pressure data is missing from .cnv". note this error.

will upload them to G drive when I get access again.

**Comment by sean-rohan-NOAA** [comment]
Guessing this means one of the necessary outputs is missing from an earlier stage?

**Comment by coleary-noaa** [comment]
yea i think so, i just can't figure out which one as i tried it with the .cnv created from data processing steps 1 - 4. This is step number 6, and number 5 (Loop Edit) gives the same error if you try it.

**Comment by coleary-noaa** [comment]
uploaded new DatCnv.psa that includes pressure output as well as Derive.psa
