### ISSUE TITLE
Appending lat/lon data for TEOS-10

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [sean-rohan-NOAA/gapctd#7]
We'll need to figure out how to setup the lat/lon data prior to TEOS-10 processing. I'm not sure if this should be done in the field or by pulling in lat/lon information from haul data afterwards. Adding lat/lon in the field seems prone to human error. Figuring it out afterwards could get messy if the CTD clock doesn't match survey time or if there are data from cases where the CTD was turned on but not deployed.

**Comment by sean-rohan-NOAA** [comment]
NMEA files with latitude/longitude for a cast are .txt files that have the same name as a .cnv file, only with a .txt ending. 

As a semi-fabricated example, the attachment is what one would use when inputting a file named SBE19_CTD8106_Hauls_Test1_Saltwater_24March2021_raw_fil1_align_tmcorrect_EOS80.cnv to DeriveTEOS10.psa:

[SBE19_CTD8106_Hauls_Test1_Saltwater_24March2021_raw_fil1_align_tmcorrect_EOS80.txt](https://github.com/sean-rohan-NOAA/gapctd/files/6288566/SBE19_CTD8106_Hauls_Test1_Saltwater_24March2021_raw_fil1_align_tmcorrect_EOS80.txt)

So the task is to set up an NMEA text file for each haul. May need to include a time buffer because the CTD will be turned on before the haul start time.

**Comment by coleary-noaa** [comment]
create_NMEA_files() function pushed should create the NMEA .txt files for each .cnv in the cnv directory. Need to test the function first before we try to integrate it into the others. 

Worth noting: 
- used the absolute minimum difference in start times for cnv vs hauls on that date in that region to match up cnv with haul  
- used the START_LATITUDE and START_LONGITUDE to fill in lat/lon. can change this depending on what we decide to do about using downcast vs upcast or both?
- started an if statement to make sure the CTD data are in the same time zone as the haul data, but they aren't in the test files so I haven't added that back in/tested that bit yet

**Comment by sean-rohan-NOAA** [comment]
- 2nd bullet: For the purposes of TEOS10, the difference doesn't matter but I think we should have properly indexed values for casts in case anyone ever gets interested in small-scale spatial variability.
- 3rd bullet: Sounds good. Based on past experience, I think we should be thinking about how to account for offsets of 1 (Pacific Time) and 8 (GMT) hours. Ideally folks will be checking for a timestamp mismatch during the survey.
